### ISSUE TITLE
Prepare for publishing

### ISSUE THREAD

**Issue by allanwalpy** [AndreyLysenkov/LousySudoku#54]
Don't ask... I just have a thought, and I have a weekness to pointless ideas
As I am working solo now, issue becomes a bit pointless, but I'll keep writing them as memo for myself
So work for know:
- [ ] #55 Add some modification to core structure
- [ ] #56 Improve WPF interface for sudoku not squard form
- [ ] #56 Check textures of WPF interface for copyright (replace them)
- [ ] #58 Add settings
- [ ] #59 Add 3D sudoku
  - [ ] Add simple interface for 3D sudoku
  - [ ] Add 3D interface for 3D sudoku (least importance)
- [ ] #56 Maybe add some music
- [ ] #57 Add manual for mods
